### ISSUE TITLE
Missing instructions for development on macOS Mojave

### ISSUE THREAD

**Issue by kytwb** [kytwb/ferdi#20]
Running `npm install` on macOS Mojave fails with the following:

```
kytwbs-MacBook-Pro:ferdi kytwb$ npm install

> macos-notification-state@1.3.1 install /Users/kytwb/Downloads/Side Projects/ferdi/node_modules/macos-notification-state
> node-gyp rebuild

  CXX(target) Release/obj.target/notificationstate/lib/notificationstate.o
  CXX(target) Release/obj.target/notificationstate/lib/notificationstate-query.o
  CXX(target) Release/obj.target/notificationstate/lib/do-not-disturb.o
  SOLINK_MODULE(target) Release/notificationstate.node
ld: malformed file
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreGraphics.framework/CoreGraphics.tbd:4:18: error: unknown enumerated scalar
platform:        zippered
                 ^~~~~~~~
 file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreGraphics.framework/CoreGraphics.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/notificationstate.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kytwb/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/kytwb/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kytwb/Downloads/Side Projects/ferdi/node_modules/macos-notification-state
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN @meetfranz/forms@1.0.16 requires a peer of react@^16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @meetfranz/forms@1.0.16 requires a peer of react-dom@16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @meetfranz/ui@0.0.9 requires a peer of react@^16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @meetfranz/ui@0.0.9 requires a peer of react-dom@16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-router@3.1.2 requires a peer of mobx@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-electron-web-view@2.0.1 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-electron-web-view@2.0.1 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macos-notification-state@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macos-notification-state@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kytwb/.npm/_logs/2019-09-06T14_51_39_192Z-debug.log
```

The solution seems to be to run the following command first:

```
$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

This could be added to the [**Preparations**](https://github.com/kytwb/ferdi/blob/9d9e8991c6729de0fe664a8f17a3c881c6bd420e/README.md#L36) section of the README (which could also be renamed **Prerequistes**).

via https://github.com/esnme/ultrajson/issues/332#issuecomment-481910514

**Comment by vantezzen** [comment]
Have you tried removing the node_modules folder and then installing dependencies using `npx lerna bootstrap`? This seems to be the recommended action by the [Franz documentation](https://github.com/meetfranz/franz#Install-dependencies)
